language: node_js
node_js: stable
before_deploy: 
- curl -sL https://ibm.biz/idt-installer | bash
deploy:
- provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: niko-dev