language: node_js
os: osx
node_js: stable
before_deploy: 
- curl -L https://clis.ng.bluemix.net/download/bluemix-cli/0.16.2/osx/archive | tar -zx
- chmod -R u+x ./IBM_Cloud_CLI
- export PATH="./IBM_Cloud_CLI:$PATH"
deploy:
  - provider: script
    script: yarn stage
    on:
      branch: master