language: node_js
os: osx
node_js: stable
before_deploy: 
- curl -sL https://ibm.biz/idt-installer | bash
deploy:
- provider: script
  skip_cleanup: true
  script: yarn stage
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: yarn stage
  on:
    branch: niko-dev