apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-for-ibmdomain-http-and-https
spec:
  tls:
  - hosts:
    -  annotations.us-east.containers.appdomain.cloud
    secretName: secret
  rules:
  - host: annotations.us-east.containers.appdomain.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: cloud-annotations-production
          servicePort: 8080
