apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: annotations
    tier: frontend
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: annotations
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: annotations
      tier: frontend
  replicas: 6
  template:
    metadata:
      labels:
        app: annotations
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: us.icr.io/bourdakos1/annotate:32ed17fc1a02c5e30366fffac24a411a731d82e2
        env:
        - name: TLS_CRT
          valueFrom:
            secretKeyRef:
              name: annotations-secret
              key: tls.crt
        - name: TLS_KEY
          valueFrom:
            secretKeyRef:
              name: annotations-secret
              key: tls.key
        ports:
        - containerPort: 8080
