apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    ingress.bluemix.net/redirect-to-https: "True"
    ingress.bluemix.net/sticky-cookie-services: "serviceName=frontend name=sticky expires=5h path=/ hash=sha1"
    ingress.bluemix.net/client-max-body-size: "size=10m"
spec:
  tls:
  - hosts:
    - annotations.ai
    - www.annotations.ai
    - cloud.annotations.ai
    secretName: annotations-secret
  - hosts:
    - annotations.us-east.containers.appdomain.cloud
    secretName: annotations
  rules:
  - host: 'annotations.ai'
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
  - host: www.annotations.ai
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
  - host: cloud.annotations.ai
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
  - host: annotations.us-east.containers.appdomain.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
